### PR TITLE
Add webrtc-http ingest protocol

### PR DESCRIPTION
**Pull request by murillo128**
This PR adds supports for a custom webrtc server implementing the webrt-http ingest protocol (whip).

It also has some minor fixes regarding ice/dtls disconnection

### CODE REVIEW

**Comment by notedit** [comment]
Where is the  "webrtc-http ingest protocol" ?


I try to write a version in Chinese.   https://github.com/rtcdn/rtcdn-draft

**Comment by murillo128** [comment]
> Where is the "webrtc-http ingest protocol" ?

I still have pending to write a draft for it, basically it is just an http post with an sdp offer and a 200 ok response with the sdp answer:

https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/m84-v23.2-whip/plugins/websocket-client/CustomWebrtcImpl.cpp#L51

Everything else is there controlled by ice contsnt freshness and dtls shutdown. A trivial example of the server side impl:
https://github.com/medooze/whip-test/blob/master/index.js

**Comment by notedit** [comment]
I very much hope that there is a draft.   Top cdn providers in china have supported webrtc-based live streaming.

**Comment by agouaillard-cosmo** [comment]
leeoxiang,

my traditional chinese is a little bit rusty, but there seems to be
interesting things in your document. (why traditional? are you based in HKG
or Taiwan?)

In terms of rtmp <==> webrtc transcoding, one thing we have added is
support to opus 5.1 (a.k.a multiopus), to be able to transcode from AAC 5.1
without losing spatial information. of course your comment about the
transmuxing (44.1 to 48) is valid.
There are other aspects that need clarifications, which we have not written
yet.
Also. your document seems to focus on RTMP/webrtc gap narrowing, so I
suppose it is focussing on ingest for CDN or social networks, right?.
In our case, we are also considering other use cases like hardware encoders
which need to have an easier, stable reference signalling in place as
updating the signalling stack will be almost impossible after delivery.

Would you be interested in co-authoring a draft with us? Would your
employer let you?

**Comment by notedit** [comment]
Hi  @agouaillard-cosmo 

I am from chinese mainland, based in Beijing.  
Our first use case is making webrtc works with cdn, so we need to do some transmuxing.  
We are planning to support more use cases,  like webrtc publishing  without audio transcode,  video conference(stream based).
I am very happy to see a draft like this and want to join this.

**Comment by agouaillard-cosmo** [comment]
ok, let s see how we can make it work.
Sergio you take the first draft please.
Leeoxiang, who is your employer so we can list affiliation.
PS used to live in WuDaoKou

**Comment by notedit** [comment]
Cool,  WuDaokou is very close to me.  
I works for Tencent(tencent.com/cloud.tencent.com).

**Comment by murillo128** [comment]
very early draft here:

https://github.com/murillo128/webrtc-http-ingest-protocol/blob/master/draf-murillo-whip.md

**Pull request merged**
